<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        $employees = [
            [
    'employee_code'              => 'EMP1000',
    'first_name'                 => 'Vishwanath',
    'last_name'                  => 'Srirangam',
    'email'                      => 'vishwanath.s@techsprout.ai',
    'phone'                      => '87909 00881',
    'dob'                        => '1981-08-26',
    'date_of_birth'              => '1981-08-26',
    'joining_date'               => '2026-01-01',
    'exit_date'                  => null,
    'employment_type'            => 'full_time',
    'status'                     => 'active',
    'blood_group'                => null,
    'department_id'              => null, // set as needed
    'designation_id'             => null, // set as needed
    'reporting_to'               => null, // set as needed
    'position_level'             => 'manager',
    'hierarchy_level'            => 5,
    'country'                    => 'India',
    'bank_name'                  => 'ICICI Bank Ltd',
    'bank_account_number'        => '042401501198',
    'bank_ifsc'                  => 'ICIC0000424',
    'bank_branch'                => 'Senapati Road',
    'pan_number'                 => 'AXRPS1984K',
    'aadhaar_number'             => '761753263419',
    'emergency_contact_phone'    => '8328617737',
    'emergency_contact_relation' => 'Laxmi',
    'basic_salary'               => 0,
],
            [
                'employee_code'              => 'EMP1001',
                'first_name'                 => 'Shakti',
                'last_name'                  => 'Sharma',
                'email'                      => 'shakti.sharma@hrportal.com', // email generated
                'phone'                      => '9182617094',
                'dob'                        => '1997-01-01',
                'date_of_birth'              => '1997-01-01',
                'joining_date'               => '2026-01-01',
                'exit_date'                  => null,
                'employment_type'            => 'full_time',
                'status'                     => 'active',
                'blood_group'                => 'B+',
                'department_id'              => 6,
                'designation_id'             => 28,
                'reporting_to'               => 1,
                'position_level'             => 'manager',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'Kotak Mahindra Bank',
                'bank_account_number'        => '8051981293',
                'bank_ifsc'                  => 'KKBK0007451',
                'bank_branch'                => 'Abid Road , Adilabad',
                'pan_number'                 => 'JZNPS0874K',
                'aadhaar_number'             => '705272108539',
                'emergency_contact_phone'    => '9110561977',
                'emergency_contact_relation' => 'Dad',
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'EMP1011',
                'first_name'                 => 'Guntuku',
                'last_name'                  => 'Akanksha',
                'email'                      => 'guntukuakanksha@gmail.com',
                'phone'                      => '9347948955',
                'dob'                        => '2001-03-20',
                'date_of_birth'              => '2001-03-20',
                'joining_date'               => '2025-10-29',
                'exit_date'                  => null,
                'employment_type'            => 'intern',
                'status'                     => 'active',
                'blood_group'                => 'B+',
                'department_id'              => 1,
                'designation_id'             => 6,
                'reporting_to'               => 1,
                'position_level'             => 'manager',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'HDFC Bank',
                'bank_account_number'        => '50100650783881',
                'bank_ifsc'                  => 'HDFC0001621',
                'bank_branch'                => 'Adilabad',
                'pan_number'                 => 'EQNPA6136G',
                'aadhaar_number'             => '232609585611',
                'emergency_contact_phone'    => '9994830577',
                'emergency_contact_relation' => 'mom',
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'EMP1003',
                'first_name'                 => 'Balam',
                'last_name'                  => 'Srinivas',
                'email'                      => 'srinivasbalam2003@gmail.com',
                'phone'                      => '9494465968',
                'dob'                        => '2003-03-06',
                'date_of_birth'              => '2003-03-06',
                'joining_date'               => '2025-07-20',
                'exit_date'                  => null,
                'employment_type'            => 'full_time',
                'status'                     => 'active',
                'blood_group'                => 'B+',
                'department_id'              => 2,
                'designation_id'             => 1,
                'reporting_to'               => 8,
                'position_level'             => 'staff',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'State Bank of India',
                'bank_account_number'        => '41592584799',
                'bank_ifsc'                  => 'SBIN0017752',
                'bank_branch'                => 'Dharmavaram',
                'pan_number'                 => 'MIDPS8543R',
                'aadhaar_number'             => '638065225721',
                'emergency_contact_phone'    => '9490362772',
                'emergency_contact_relation' => 'Dad',
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'EMP1005',
                'first_name'                 => 'SomiSetty',
                'last_name'                  => 'Sai Varun',
                'email'                      => 'somisettysaivarun@gmail.com',
                'phone'                      => '9959512065',
                'dob'                        => '2004-03-14',
                'date_of_birth'              => '2004-03-14',
                'joining_date'               => '2025-07-16',
                'exit_date'                  => null,
                'employment_type'            => 'full_time',
                'status'                     => 'active',
                'blood_group'                => 'O+',
                'department_id'              => 2,
                'designation_id'             => 1,
                'reporting_to'               => 1,
                'position_level'             => 'staff',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'IndusInd Bank',
                'bank_account_number'        => '159959512065',
                'bank_ifsc'                  => 'INDB0001680',
                'bank_branch'                => 'Hastinapuram',
                'pan_number'                 => 'PCNPS6012J',
                'aadhaar_number'             => '850609206695',
                'emergency_contact_phone'    => '8121555620',
                'emergency_contact_relation' => 'Mom',
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'EMP1008',
                'first_name'                 => 'Sowndarya',
                'last_name'                  => 'Tamilmani',
                'email'                      => 'rsowndarya2497@gmail.com',
                'phone'                      => '9087606910',
                'dob'                        => '1997-05-24',
                'date_of_birth'              => '1997-05-24',
                'joining_date'               => '2025-07-30',
                'exit_date'                  => null,
                'employment_type'            => 'full_time',
                'status'                     => 'active',
                'blood_group'                => 'A+',
                'department_id'              => 4,
                'designation_id'             => 15,
                'reporting_to'               => 9,
                'position_level'             => 'staff',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'State Bank of India',
                'bank_account_number'        => '38772592020',
                'bank_ifsc'                  => 'SBIN0011068',
                'bank_branch'                => 'Madurai bypass',
                'pan_number'                 => 'LAUPS3986E',
                'aadhaar_number'             => '280817190477',
                'emergency_contact_phone'    => '9500484843',
                'emergency_contact_relation' => 'Husband',
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'EMP1002',
                'first_name'                 => 'Ryagati',
                'last_name'                  => 'Venkatesh',
                'email'                      => 'Heyvenkat25@gmail.com',
                'phone'                      => '9121430545',
                'dob'                        => '2001-04-17',
                'date_of_birth'              => '2001-04-17',
                'joining_date'               => '2025-09-06',
                'exit_date'                  => null,
                'employment_type'            => 'intern',
                'status'                     => 'active',
                'blood_group'                => null,
                'department_id'              => 4,
                'designation_id'             => 15,
                'reporting_to'               => 9,
                'position_level'             => 'staff',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'State Bank of India',
                'bank_account_number'        => '62324548380',
                'bank_ifsc'                  => 'SBIN0021593',
                'bank_branch'                => 'Galipalli',
                'pan_number'                 => 'FCEPR5099P',
                'aadhaar_number'             => '875585264025',
                'emergency_contact_phone'    => null,
                'emergency_contact_relation' => null,
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'EMP1004',
                'first_name'                 => 'Karipe',
                'last_name'                  => 'Neeraj Kumar',
                'email'                      => 'karipeneerajkumar2@gmail.com',
                'phone'                      => '9182286593',
                'dob'                        => '2005-09-05',
                'date_of_birth'              => '2005-09-05',
                'joining_date'               => '2025-07-02',
                'exit_date'                  => null,
                'employment_type'            => 'intern',
                'status'                     => 'active',
                'blood_group'                => 'AB-',
                'department_id'              => 2,
                'designation_id'             => 1,
                'reporting_to'               => 1,
                'position_level'             => 'staff',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'State Bank of India',
                'bank_account_number'        => '44824583238',
                'bank_ifsc'                  => 'SBIN0040647',
                'bank_branch'                => 'Dharmareddy Colony',
                'pan_number'                 => 'OWXPK8039L',
                'aadhaar_number'             => '724403475112',
                'emergency_contact_phone'    => '9246604685',
                'emergency_contact_relation' => 'Dad',
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'EMP1013',
                'first_name'                 => 'Dommeti',
                'last_name'                  => 'Yamini',
                'email'                      => 'yamini.d031@gmail.com',
                'phone'                      => '7989451108',
                'dob'                        => '2001-07-31',
                'date_of_birth'              => '2001-07-31',
                'joining_date'               => '2025-11-17',
                'exit_date'                  => null,
                'employment_type'            => 'full_time',
                'status'                     => 'active',
                'blood_group'                => 'O-',
                'department_id'              => 6,
                'designation_id'             => 14,
                'reporting_to'               => 9,
                'position_level'             => 'staff',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'State Bank of India',
                'bank_account_number'        => '40793577791',
                'bank_ifsc'                  => 'SBIN0007087',
                'bank_branch'                => 'Pedagantyada',
                'pan_number'                 => 'BWAPY1646P',
                'aadhaar_number'             => '280837296376',
                'emergency_contact_phone'    => '9000322719',
                'emergency_contact_relation' => 'Dad',
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'EMP1024',
                'first_name'                 => 'Vasa',
                'last_name'                  => 'Raviteja',
                'email'                      => 'vasa.raviteja@gmail.com',
                'phone'                      => '9177746447',
                'dob'                        => '1990-05-21',
                'date_of_birth'              => '1990-05-21',
                'joining_date'               => '2026-04-03',
                'exit_date'                  => null,
                'employment_type'            => 'full_time',
                'status'                     => 'active',
                'blood_group'                => null,
                'department_id'              => 4,
                'designation_id'             => 11,
                'reporting_to'               => 1,
                'position_level'             => 'manager',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'ICICI Bank',
                'bank_account_number'        => '112001512446',
                'bank_ifsc'                  => 'ICIC0001120',
                'bank_branch'                => 'Kavuri, Begumpet',
                'pan_number'                 => 'APIPV7125A',
                'aadhaar_number'             => '989534387415',
                'emergency_contact_phone'    => null,
                'emergency_contact_relation' => null,
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'EMP1012',
                'first_name'                 => 'C.Albet',
                'last_name'                  => 'Simson',
                'email'                      => 'simson.albet0227@gmail.com',
                'phone'                      => '7780708582',
                'dob'                        => '1997-04-27',
                'date_of_birth'              => '1997-04-27',
                'joining_date'               => '2025-11-17',
                'exit_date'                  => null,
                'employment_type'            => 'full_time',
                'status'                     => 'active',
                'blood_group'                => null,
                'department_id'              => 6,
                'designation_id'             => 14,
                'reporting_to'               => 9,
                'position_level'             => 'staff',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'HDFC Bank',
                'bank_account_number'        => '50100478861432',
                'bank_ifsc'                  => 'HDFC0002391',
                'bank_branch'                => 'Banjara Hills',
                'pan_number'                 => 'CWJPA6393P',
                'aadhaar_number'             => '819693691787',
                'emergency_contact_phone'    => '6301204241',
                'emergency_contact_relation' => 'Wife',
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'EMP1006',
                'first_name'                 => 'Anchala',
                'last_name'                  => 'Niharika',
                'email'                      => 'anchalaniharika@gmail.com',
                'phone'                      => '9381193375',
                'dob'                        => '2002-02-07',
                'date_of_birth'              => '2002-02-07',
                'joining_date'               => '2025-07-16',
                'exit_date'                  => null,
                'employment_type'            => 'intern',
                'status'                     => 'active',
                'blood_group'                => null,
                'department_id'              => 2,
                'designation_id'             => 1,
                'reporting_to'               => 8,
                'position_level'             => 'staff',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'State Bank of India',
                'bank_account_number'        => '42592301646',
                'bank_ifsc'                  => 'SBIN0002746',
                'bank_branch'                => 'R S Kondapuram',
                'pan_number'                 => 'FJAPA0465B',
                'aadhaar_number'             => '359399331717',
                'emergency_contact_phone'    => null,
                'emergency_contact_relation' => null,
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'EMP1018',
                'first_name'                 => 'Chaitanya',
                'last_name'                  => 'Kumar Jinka',
                'email'                      => 'jckumar99@gmail.com',
                'phone'                      => '8143005483',
                'dob'                        => '1994-10-01',
                'date_of_birth'              => '1994-10-01',
                'joining_date'               => '2025-12-15',
                'exit_date'                  => null,
                'employment_type'            => 'intern',
                'status'                     => 'active',
                'blood_group'                => 'B+',
                'department_id'              => 4,
                'designation_id'             => 5,
                'reporting_to'               => 1,
                'position_level'             => 'intern',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'State Bank of India',
                'bank_account_number'        => '32653801068',
                'bank_ifsc'                  => 'SBIN0000901',
                'bank_branch'                => 'Proddatur Main Branch',
                'pan_number'                 => 'BVIPJ8057Q',
                'aadhaar_number'             => '238902897570',
                'emergency_contact_phone'    => '9949645898',
                'emergency_contact_relation' => 'Dad',
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'EMP1019',
                'first_name'                 => 'Santosh',
                'last_name'                  => 'Asole',
                'email'                      => 'santoshasole9@gmail.com',
                'phone'                      => '7666615729',
                'dob'                        => '1997-01-27',
                'date_of_birth'              => '1997-01-27',
                'joining_date'               => '2025-12-22',
                'exit_date'                  => null,
                'employment_type'            => 'full_time',
                'status'                     => 'active',
                'blood_group'                => null,
                'department_id'              => 2,
                'designation_id'             => 3,
                'reporting_to'               => 1,
                'position_level'             => 'manager',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'ICICI Bank',
                'bank_account_number'        => '697001505866',
                'bank_ifsc'                  => 'ICIC0006970',
                'bank_branch'                => 'Beed Bypass,Aurangabad',
                'pan_number'                 => 'CQCPA8664G',
                'aadhaar_number'             => '255750648461',
                'emergency_contact_phone'    => '9767455653',
                'emergency_contact_relation' => 'Dad',
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'EMP1020',
                'first_name'                 => 'Anchula',
                'last_name'                  => 'Naga Jyothi',
                'email'                      => 'nagajyothianchula@gmail.com',
                'phone'                      => '9390623676',
                'dob'                        => '2001-01-07',
                'date_of_birth'              => '2001-01-07',
                'joining_date'               => '2025-12-29',
                'exit_date'                  => null,
                'employment_type'            => 'intern',
                'status'                     => 'active',
                'blood_group'                => 'B+',
                'department_id'              => 4,
                'designation_id'             => 5,
                'reporting_to'               => 1,
                'position_level'             => 'intern',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'Indian Overseas Bank',
                'bank_account_number'        => '33301000023965',
                'bank_ifsc'                  => 'IOBA0000333',
                'bank_branch'                => 'Thullur',
                'pan_number'                 => 'EFNPA4114M',
                'aadhaar_number'             => '318277513332',
                'emergency_contact_phone'    => '8499020987',
                'emergency_contact_relation' => 'Husband',
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'EMP1022',
                'first_name'                 => 'Rajoli',
                'last_name'                  => 'Ragini',
                'email'                      => 'raginireddy6666@gmail.com',
                'phone'                      => '7670933462',
                'dob'                        => '2003-05-02',
                'date_of_birth'              => '2003-05-02',
                'joining_date'               => '2026-03-01',
                'exit_date'                  => null,
                'employment_type'            => 'intern',
                'status'                     => 'active',
                'blood_group'                => 'O+',
                'department_id'              => 4,
                'designation_id'             => 5,
                'reporting_to'               => 1,
                'position_level'             => 'intern',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'Union Bank of India',
                'bank_account_number'        => '140910100100431',
                'bank_ifsc'                  => 'UBIN0814091',
                'bank_branch'                => 'Vempalli',
                'pan_number'                 => 'DSJPR7567H',
                'aadhaar_number'             => '999039032321',
                'emergency_contact_phone'    => '9912528554-Dad',
                'emergency_contact_relation' => null,
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'EMP1023',
                'first_name'                 => 'Kenchugundi',
                'last_name'                  => 'Sandesh',
                'email'                      => 'sandeshkenchugundi01@gmail.com',
                'phone'                      => '9160903500',
                'dob'                        => '2000-01-12',
                'date_of_birth'              => '2000-01-12',
                'joining_date'               => '2026-01-02',
                'exit_date'                  => null,
                'employment_type'            => 'intern',
                'status'                     => 'active',
                'blood_group'                => 'O+',
                'department_id'              => 2,
                'designation_id'             => 1,
                'reporting_to'               => 8,
                'position_level'             => 'staff',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'State Bank of India',
                'bank_account_number'        => '62436942785',
                'bank_ifsc'                  => 'SBIN0004693',
                'bank_branch'                => 'Ieeja',
                'pan_number'                 => 'NSCPS1866P',
                'aadhaar_number'             => '236411349044',
                'emergency_contact_phone'    => '7799506901',
                'emergency_contact_relation' => 'Dad',
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'EMP1025',
                'first_name'                 => 'Chitturi',
                'last_name'                  => 'Durga Kishore',
                'email'                      => 'chitturidurgakishore@gmail.com',
                'phone'                      => '8978397465',
                'dob'                        => null,
                'date_of_birth'              => null,
                'joining_date'               => '2026-09-03',
                'exit_date'                  => null,
                'employment_type'            => 'intern',
                'status'                     => 'active',
                'blood_group'                => 'B+',
                'department_id'              => 2,
                'designation_id'             => 1,
                'reporting_to'               => 8,
                'position_level'             => 'staff',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'State Bank of India',
                'bank_account_number'        => '38881338580',
                'bank_ifsc'                  => 'SBIN0021360',
                'bank_branch'                => 'Gayatri Nagar',
                'pan_number'                 => 'CQLPC5286R',
                'aadhaar_number'             => '834208740375',
                'emergency_contact_phone'    => '7995015177',
                'emergency_contact_relation' => 'Mom',
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'TEMP_NANDINI',
                'first_name'                 => 'Nandini',
                'last_name'                  => '',
                'email'                      => 'nandini@hrportal.com', // email generated
                'phone'                      => '9346499300',
                'dob'                        => '2000-05-13',
                'date_of_birth'              => '2000-05-13',
                'joining_date'               => '2025-01-01',
                'exit_date'                  => null,
                'employment_type'            => 'intern',
                'status'                     => 'active',
                'blood_group'                => 'A+',
                'department_id'              => 4,
                'designation_id'             => 5,
                'reporting_to'               => 1,
                'position_level'             => 'intern',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => null,
                'bank_account_number'        => null,
                'bank_ifsc'                  => null,
                'bank_branch'                => null,
                'pan_number'                 => null,
                'aadhaar_number'             => null,
                'emergency_contact_phone'    => '9160444299',
                'emergency_contact_relation' => 'Mom',
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'TEMP_SAILINGA',
                'first_name'                 => 'Sailinga',
                'last_name'                  => '',
                'email'                      => 'sailinga@hrportal.com', // email generated
                'phone'                      => '7569784363',
                'dob'                        => '2002-03-29',
                'date_of_birth'              => '2002-03-29',
                'joining_date'               => '2026-01-04',
                'exit_date'                  => null,
                'employment_type'            => 'intern',
                'status'                     => 'active',
                'blood_group'                => 'A-',
                'department_id'              => 2,
                'designation_id'             => 1,
                'reporting_to'               => 8,
                'position_level'             => 'staff',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => null,
                'bank_account_number'        => null,
                'bank_ifsc'                  => null,
                'bank_branch'                => null,
                'pan_number'                 => 'ATZPL7148J',
                'aadhaar_number'             => '431935595050',
                'emergency_contact_phone'    => '9494082575',
                'emergency_contact_relation' => 'Dad',
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'TEMP_NAVEEN_B',
                'first_name'                 => 'Naveen',
                'last_name'                  => 'Batta',
                'email'                      => 'naveen.batta@hrportal.com', // email generated
                'phone'                      => '7288099381',
                'dob'                        => '2001-09-08',
                'date_of_birth'              => '2001-09-08',
                'joining_date'               => '2026-04-27',
                'exit_date'                  => null,
                'employment_type'            => 'intern',
                'status'                     => 'active',
                'blood_group'                => 'O+',
                'department_id'              => 2,
                'designation_id'             => 1,
                'reporting_to'               => 1,
                'position_level'             => 'staff',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => null,
                'bank_account_number'        => null,
                'bank_ifsc'                  => null,
                'bank_branch'                => null,
                'pan_number'                 => 'DVCPB7726Q',
                'aadhaar_number'             => '646592116576',
                'emergency_contact_phone'    => '9908875182',
                'emergency_contact_relation' => 'Dad',
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'TEMP_DURGA_DE',
                'first_name'                 => 'Durga',
                'last_name'                  => 'devi',
                'email'                      => 'kdevi1229@gmail.com',
                'phone'                      => '7981626640',
                'dob'                        => '1991-01-05',
                'date_of_birth'              => '1991-01-05',
                'joining_date'               => '2026-04-05',
                'exit_date'                  => '2026-05-13',
                'employment_type'            => 'intern',
                'status'                     => 'active',
                'blood_group'                => 'A+',
                'department_id'              => 4,
                'designation_id'             => 14,
                'reporting_to'               => 1,
                'position_level'             => 'staff',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'ICICI Bank',
                'bank_account_number'        => '7501582070',
                'bank_ifsc'                  => 'ICIC0000075',
                'bank_branch'                => 'S.R.Nagar',
                'pan_number'                 => 'EESPK2102H',
                'aadhaar_number'             => '318927408675',
                'emergency_contact_phone'    => '9494919999',
                'emergency_contact_relation' => 'Husband',
                'basic_salary'               => 0,
            ],
            [
                'employee_code'              => 'EMP1026',
                'first_name'                 => 'Ladhwe',
                'last_name'                  => 'Navaneetha',
                'email'                      => 'ladhwenavaneetha@gmail.com',
                'phone'                      => '9182072848',
                'dob'                        => '1998-07-10',
                'date_of_birth'              => '1998-07-10',
                'joining_date'               => '2026-05-15',
                'exit_date'                  => null,
                'employment_type'            => 'full_time',
                'status'                     => 'active',
                'blood_group'                => 'O+',
                'department_id'              => 4,
                'designation_id'             => 15,
                'reporting_to'               => 1,
                'position_level'             => 'manager',
                'hierarchy_level'            => 5,
                'country'                    => 'India',
                'bank_name'                  => 'Kotak Mahindra Bank',
                'bank_account_number'        => '5950533516',
                'bank_ifsc'                  => 'KKBK0007451',
                'bank_branch'                => 'ABID Road, Hyderabad',
                'pan_number'                 => 'BMKPL5251R',
                'aadhaar_number'             => '669118845090',
                'emergency_contact_phone'    => '9182617094',
                'emergency_contact_relation' => null,
                'basic_salary'               => 0,
            ],
        ];

        foreach ($employees as $data) {
            // Skip if employee_code already exists
            if (Employee::where('employee_code', $data['employee_code'])->exists()) {
                $this->command->warn("Skipping {$data['employee_code']} - already exists.");
                continue;
            }

            // Also skip if email already exists
            if (Employee::where('email', $data['email'])->exists()) {
                $this->command->warn("Skipping {$data['email']} - email already exists.");
                continue;
            }

            // Create employee
            $employee = Employee::create($data);

            // Create user account (for portal login)
            if (!User::where('email', $data['email'])->exists()) {
                $firstName = $data['first_name'];
                $lastName  = $data['last_name'];

                $user = User::create([
                    'name'        => "{$firstName} {$lastName}",
                    'email'       => $data['email'],
                    'password'    => Hash::make('Employee@123'),
                    'role'        => 'employee',
                    'status'      => 'active',
                    'employee_id' => $employee->id,
                ]);

                // Assign Spatie role
                $user->assignRole('employee');

                // Link user back to employee
                $employee->update(['user_id' => $user->id]);

                $this->command->info("✅ Created: {$data['employee_code']} | {$firstName} {$lastName} | {$data['email']}");
            }
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $this->command->info('');
        $this->command->info('🎉 Employee seeding complete!');
        $this->command->info('🔑 Default password for all employees: Employee@123');
    }
}